services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    container_name: aadevcache
    command: redis-server --appendonly yes

    ports:
      - "6375:6379"

    volumes:
      - aa_dev_redis_volume:/data

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    container_name: aadevdb

    environment:
      POSTGRES_DB: aateste
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5435:5432"

    volumes:
      - aa_dev_postgres_volume:/var/lib/postgresql/data

    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    container_name: aadevmail
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

volumes:
  aa_dev_redis_volume:
  aa_dev_postgres_volume:
